name: Angular Build and Docker Image

on:
  push:
    branches:
      - main

jobs:

  generate-environment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Set Execute Permissions
        run: chmod +x generate-environment-file.sh

      - name: Generate Environment File
        run: ./generate-environment-file.sh "${{ secrets.API_URL }}" "${{ secrets.OKTA_DOMAIN }}" "${{ secrets.CLIENT_ID }}"

  build:
    runs-on: ubuntu-latest
    environment: dev
    needs: generate-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set Execute Permissions
        run: chmod +x generate-environment-file.sh

      - name: Generate Environment File
        run: ./generate-environment-file.sh "${{ secrets.API_URL }}" "${{ secrets.OKTA_DOMAIN }}" "${{ secrets.CLIENT_ID }}"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/businessschool-web:latest \
            -f Dockerfile \
            .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/businessschool-web:latest

  